name: maccabi_assignment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

